# https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

[build]
publish = "public"
command = "hugo --gc --minify"

# Ref:
#   https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# Note: You can also set `HUGO_VERSION` via the console:
#   https://app.netlify.com/sites/foo-bar-baz/settings/deploys#environment
# but the value(s) here take precedence.
[context.deploy-preview.environment]
HUGO_VERSION = "0.66.0"

[context.production.environment]
HUGO_VERSION = "0.66.0"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"

